<?php

use Illuminate\Database\Seeder;

class AbilitiesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('abilities')->delete();
        
        \DB::table('abilities')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Flutter',
                'base_class' => NULL,
                'behaviour' => '["DOTA_ABILITY_BEHAVIOR_NO_TARGET","DOTA_ABILITY_BEHAVIOR_IMMEDIATE"]',
                'type' => 'DOTA_ABILITY_TYPE_BASIC',
                'texture_name' => NULL,
                'deny_self_cast' => 1,
                'cast_hidden' => 0,
                'target_team' => NULL,
                'target_type' => NULL,
                'target_flags' => NULL,
                'damage_type' => NULL,
                'damage' => NULL,
                'mana_cost' => NULL,
                'gold_cost' => NULL,
                'cooldown' => '["25"]',
                'cast_range' => NULL,
                'cast_point' => NULL,
                'cast_range_buffer' => NULL,
                'channel_time' => NULL,
                'channel_mana_cost' => NULL,
                'duration' => '["5"]',
                'cooldown_group' => NULL,
                'created_at' => '2017-03-06 12:00:00',
                'updated_at' => '2017-03-06 13:26:05',
                'magic_stick' => 1,
                'is_override' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Energy burst',
                'base_class' => NULL,
                'behaviour' => '["DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"]',
                'type' => 'DOTA_ABILITY_TYPE_BASIC',
                'texture_name' => 'item_dagon',
                'deny_self_cast' => 1,
                'cast_hidden' => 0,
                'target_team' => '["DOTA_UNIT_TARGET_TEAM_ENEMY"]',
                'target_type' => '["DOTA_UNIT_TARGET_HERO","DOTA_UNIT_TARGET_BASIC"]',
                'target_flags' => NULL,
                'damage_type' => NULL,
                'damage' => '["400","500","600","700","800","1000","1500","2250","3000"]',
                'mana_cost' => '["180"]',
                'gold_cost' => NULL,
                'cooldown' => '["35","30","25","20","15","15","15","13","10"]',
                'cast_range' => '["600","650","700","750","800","850","900","950","1000"]',
                'cast_point' => '["0.0"]',
                'cast_range_buffer' => NULL,
                'channel_time' => NULL,
                'channel_mana_cost' => NULL,
                'duration' => NULL,
                'cooldown_group' => 'dagon',
                'created_at' => '2017-03-06 14:44:52',
                'updated_at' => '2017-03-06 17:10:55',
                'magic_stick' => 1,
                'is_override' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Charge Avatar',
                'base_class' => 'item_datadriven',
                'behaviour' => '["DOTA_ABILITY_BEHAVIOR_NO_TARGET","DOTA_ABILITY_BEHAVIOR_IMMEDIATE"]',
                'type' => 'DOTA_ABILITY_TYPE_BASIC',
                'texture_name' => 'item_black_king_bar',
                'deny_self_cast' => 0,
                'cast_hidden' => 0,
                'target_team' => NULL,
                'target_type' => NULL,
                'target_flags' => NULL,
                'damage_type' => NULL,
                'damage' => NULL,
                'mana_cost' => NULL,
                'gold_cost' => NULL,
                'cooldown' => '["13"]',
                'cast_range' => '["1200"]',
                'cast_point' => '["0.0"]',
                'cast_range_buffer' => NULL,
                'channel_time' => NULL,
                'channel_mana_cost' => NULL,
                'duration' => '["0.1"]',
                'cooldown_group' => 'bkb',
                'created_at' => '2017-03-08 10:03:23',
                'updated_at' => '2017-03-08 10:03:23',
                'magic_stick' => 0,
                'is_override' => 0,
            ),
            3 => 
            array (
                'id' => 5,
                'name' => 'Greater Restore',
                'base_class' => 'item_datadriven',
                'behaviour' => '["DOTA_ABILITY_BEHAVIOR_NO_TARGET","DOTA_ABILITY_BEHAVIOR_IMMEDIATE"]',
                'type' => 'DOTA_ABILITY_TYPE_BASIC',
                'texture_name' => 'item_guardian_greaves',
                'deny_self_cast' => 0,
                'cast_hidden' => 0,
                'target_team' => NULL,
                'target_type' => NULL,
                'target_flags' => NULL,
                'damage_type' => NULL,
                'damage' => NULL,
                'mana_cost' => NULL,
                'gold_cost' => NULL,
                'cooldown' => '["40"]',
                'cast_range' => '["900"]',
                'cast_point' => '["0.0"]',
                'cast_range_buffer' => NULL,
                'channel_time' => NULL,
                'channel_mana_cost' => NULL,
                'duration' => NULL,
                'cooldown_group' => 'mekanzm',
                'created_at' => '2017-03-13 08:05:20',
                'updated_at' => '2017-03-13 08:05:20',
                'magic_stick' => 1,
                'is_override' => 0,
            ),
            4 => 
            array (
                'id' => 6,
                'name' => 'Preemptive Move',
                'base_class' => 'ability_preempt',
                'behaviour' => '["DOTA_ABILITY_BEHAVIOR_NO_TARGET","DOTA_ABILITY_BEHAVIOR_IMMEDIATE"]',
                'type' => 'DOTA_ABILITY_TYPE_BASIC',
                'texture_name' => NULL,
                'deny_self_cast' => 0,
                'cast_hidden' => 1,
                'target_team' => NULL,
                'target_type' => NULL,
                'target_flags' => NULL,
                'damage_type' => NULL,
                'damage' => NULL,
                'mana_cost' => NULL,
                'gold_cost' => NULL,
                'cooldown' => '["30"]',
                'cast_range' => NULL,
                'cast_point' => '["0.0"]',
                'cast_range_buffer' => NULL,
                'channel_time' => NULL,
                'channel_mana_cost' => NULL,
                'duration' => '["0.5"]',
                'cooldown_group' => 'reflex_core',
                'created_at' => '2017-03-21 14:15:01',
                'updated_at' => '2017-03-21 14:35:39',
                'magic_stick' => 1,
                'is_override' => 0,
            ),
            5 => 
            array (
                'id' => 7,
                'name' => 'Dispeling Preemptive Move',
                'base_class' => 'ability_preempt_2',
                'behaviour' => '["DOTA_ABILITY_BEHAVIOR_NO_TARGET","DOTA_ABILITY_BEHAVIOR_IMMEDIATE"]',
                'type' => 'DOTA_ABILITY_TYPE_BASIC',
                'texture_name' => NULL,
                'deny_self_cast' => 0,
                'cast_hidden' => 1,
                'target_team' => NULL,
                'target_type' => NULL,
                'target_flags' => '["DOTA_UNIT_TARGET_FLAG_INVULNERABLE"]',
                'damage_type' => NULL,
                'damage' => NULL,
                'mana_cost' => NULL,
                'gold_cost' => NULL,
                'cooldown' => '["30"]',
                'cast_range' => NULL,
                'cast_point' => '["0.0"]',
                'cast_range_buffer' => NULL,
                'channel_time' => NULL,
                'channel_mana_cost' => NULL,
                'duration' => '["2"]',
                'cooldown_group' => 'reflex_core',
                'created_at' => '2017-03-21 14:23:46',
                'updated_at' => '2017-03-21 15:30:11',
                'magic_stick' => 1,
                'is_override' => 0,
            ),
            6 => 
            array (
                'id' => 8,
                'name' => 'Preemptive Invunearbilty',
                'base_class' => 'ability_preempt_2b',
                'behaviour' => '["DOTA_ABILITY_BEHAVIOR_NO_TARGET","DOTA_ABILITY_BEHAVIOR_IMMEDIATE"]',
                'type' => 'DOTA_ABILITY_TYPE_BASIC',
                'texture_name' => NULL,
                'deny_self_cast' => 0,
                'cast_hidden' => 1,
                'target_team' => NULL,
                'target_type' => NULL,
                'target_flags' => '["DOTA_UNIT_TARGET_FLAG_INVULNERABLE"]',
                'damage_type' => NULL,
                'damage' => NULL,
                'mana_cost' => NULL,
                'gold_cost' => NULL,
                'cooldown' => '["30"]',
                'cast_range' => NULL,
                'cast_point' => '["0.0"]',
                'cast_range_buffer' => NULL,
                'channel_time' => NULL,
                'channel_mana_cost' => NULL,
                'duration' => '["2"]',
                'cooldown_group' => 'reflex_core',
                'created_at' => '2017-03-21 14:36:37',
                'updated_at' => '2017-03-21 15:30:13',
                'magic_stick' => 1,
                'is_override' => 0,
            ),
            7 => 
            array (
                'id' => 9,
                'name' => 'Greater Dispeling Preemptive Move',
                'base_class' => 'ability_preempt_3',
                'behaviour' => '["DOTA_ABILITY_BEHAVIOR_NO_TARGET","DOTA_ABILITY_BEHAVIOR_IMMEDIATE"]',
                'type' => 'DOTA_ABILITY_TYPE_BASIC',
                'texture_name' => NULL,
                'deny_self_cast' => 0,
                'cast_hidden' => 1,
                'target_team' => NULL,
                'target_type' => NULL,
                'target_flags' => '["DOTA_UNIT_TARGET_FLAG_INVULNERABLE"]',
                'damage_type' => NULL,
                'damage' => NULL,
                'mana_cost' => NULL,
                'gold_cost' => NULL,
                'cooldown' => '["30"]',
                'cast_range' => NULL,
                'cast_point' => '["0.0"]',
                'cast_range_buffer' => NULL,
                'channel_time' => NULL,
                'channel_mana_cost' => NULL,
                'duration' => '["4"]',
                'cooldown_group' => 'reflex_core',
                'created_at' => '2017-03-21 14:46:28',
                'updated_at' => '2017-03-21 15:30:15',
                'magic_stick' => 1,
                'is_override' => 0,
            ),
            8 => 
            array (
                'id' => 10,
                'name' => 'Greater Preemptive Invunearbilty',
                'base_class' => 'ability_preempt_3b',
                'behaviour' => '["DOTA_ABILITY_BEHAVIOR_NO_TARGET","DOTA_ABILITY_BEHAVIOR_IMMEDIATE"]',
                'type' => 'DOTA_ABILITY_TYPE_BASIC',
                'texture_name' => NULL,
                'deny_self_cast' => 0,
                'cast_hidden' => 0,
                'target_team' => NULL,
                'target_type' => NULL,
                'target_flags' => '["DOTA_UNIT_TARGET_FLAG_INVULNERABLE"]',
                'damage_type' => NULL,
                'damage' => NULL,
                'mana_cost' => NULL,
                'gold_cost' => NULL,
                'cooldown' => '["30"]',
                'cast_range' => NULL,
                'cast_point' => '["0.0"]',
                'cast_range_buffer' => NULL,
                'channel_time' => NULL,
                'channel_mana_cost' => NULL,
                'duration' => '["2"]',
                'cooldown_group' => 'reflex_core',
                'created_at' => '2017-03-21 14:59:42',
                'updated_at' => '2017-03-21 15:30:17',
                'magic_stick' => 0,
                'is_override' => 0,
            ),
            9 => 
            array (
                'id' => 11,
                'name' => 'Preemptive Bubble',
                'base_class' => 'ability_preempt_3c',
                'behaviour' => '["DOTA_ABILITY_BEHAVIOR_NO_TARGET","DOTA_ABILITY_BEHAVIOR_IMMEDIATE"]',
                'type' => 'DOTA_ABILITY_TYPE_BASIC',
                'texture_name' => NULL,
                'deny_self_cast' => 0,
                'cast_hidden' => 1,
                'target_team' => NULL,
                'target_type' => NULL,
                'target_flags' => '["DOTA_UNIT_TARGET_FLAG_INVULNERABLE"]',
                'damage_type' => NULL,
                'damage' => NULL,
                'mana_cost' => NULL,
                'gold_cost' => NULL,
                'cooldown' => '["30"]',
                'cast_range' => NULL,
                'cast_point' => '["0.0"]',
                'cast_range_buffer' => NULL,
                'channel_time' => NULL,
                'channel_mana_cost' => NULL,
                'duration' => '["3"]',
                'cooldown_group' => 'reflex_core',
                'created_at' => '2017-03-21 15:08:41',
                'updated_at' => '2017-03-21 15:30:20',
                'magic_stick' => 1,
                'is_override' => 0,
            ),
            10 => 
            array (
                'id' => 12,
                'name' => 'Reactive Invunerability',
                'base_class' => 'ability_react',
                'behaviour' => '["DOTA_ABILITY_BEHAVIOR_NO_TARGET","DOTA_ABILITY_BEHAVIOR_IMMEDIATE"]',
                'type' => 'DOTA_ABILITY_TYPE_BASIC',
                'texture_name' => NULL,
                'deny_self_cast' => 0,
                'cast_hidden' => 1,
                'target_team' => NULL,
                'target_type' => NULL,
                'target_flags' => '["DOTA_UNIT_TARGET_FLAG_INVULNERABLE"]',
                'damage_type' => NULL,
                'damage' => NULL,
                'mana_cost' => NULL,
                'gold_cost' => NULL,
                'cooldown' => '["30"]',
                'cast_range' => NULL,
                'cast_point' => '["0.0"]',
                'cast_range_buffer' => NULL,
                'channel_time' => NULL,
                'channel_mana_cost' => NULL,
                'duration' => '["0.5"]',
                'cooldown_group' => 'reflex_core',
                'created_at' => '2017-03-21 15:31:06',
                'updated_at' => '2017-03-21 15:31:32',
                'magic_stick' => 1,
                'is_override' => 0,
            ),
            11 => 
            array (
                'id' => 13,
                'name' => 'Greater Reactive Invunerability',
                'base_class' => 'abulity_react_2',
                'behaviour' => '["DOTA_ABILITY_BEHAVIOR_NO_TARGET","DOTA_ABILITY_BEHAVIOR_IMMEDIATE"]',
                'type' => 'DOTA_ABILITY_TYPE_BASIC',
                'texture_name' => NULL,
                'deny_self_cast' => 0,
                'cast_hidden' => 1,
                'target_team' => NULL,
                'target_type' => NULL,
                'target_flags' => '["DOTA_UNIT_TARGET_FLAG_INVULNERABLE"]',
                'damage_type' => NULL,
                'damage' => NULL,
                'mana_cost' => NULL,
                'gold_cost' => NULL,
                'cooldown' => '["30"]',
                'cast_range' => NULL,
                'cast_point' => '["0.0"]',
                'cast_range_buffer' => NULL,
                'channel_time' => NULL,
                'channel_mana_cost' => NULL,
                'duration' => '["0.5"]',
                'cooldown_group' => 'reflex_core',
                'created_at' => '2017-03-21 15:43:42',
                'updated_at' => '2017-03-21 15:43:42',
                'magic_stick' => 1,
                'is_override' => 0,
            ),
            12 => 
            array (
                'id' => 14,
                'name' => 'Slippery Reactive Move',
                'base_class' => 'ability_react_2b',
                'behaviour' => '["DOTA_ABILITY_BEHAVIOR_NO_TARGET","DOTA_ABILITY_BEHAVIOR_IMMEDIATE"]',
                'type' => 'DOTA_ABILITY_TYPE_BASIC',
                'texture_name' => NULL,
                'deny_self_cast' => 0,
                'cast_hidden' => 1,
                'target_team' => NULL,
                'target_type' => NULL,
                'target_flags' => '["DOTA_UNIT_TARGET_FLAG_INVULNERABLE"]',
                'damage_type' => NULL,
                'damage' => NULL,
                'mana_cost' => NULL,
                'gold_cost' => NULL,
                'cooldown' => '["30"]',
                'cast_range' => NULL,
                'cast_point' => '["0.0"]',
                'cast_range_buffer' => NULL,
                'channel_time' => NULL,
                'channel_mana_cost' => NULL,
                'duration' => '["0.5"]',
                'cooldown_group' => 'reflex_core',
                'created_at' => '2017-03-21 16:13:56',
                'updated_at' => '2017-03-21 16:13:56',
                'magic_stick' => 1,
                'is_override' => 0,
            ),
            13 => 
            array (
                'id' => 15,
                'name' => 'Blinking Reflex',
                'base_class' => 'ability_react_3b',
                'behaviour' => '["DOTA_ABILITY_BEHAVIOR_NO_TARGET","DOTA_ABILITY_BEHAVIOR_IMMEDIATE"]',
                'type' => 'DOTA_ABILITY_TYPE_BASIC',
                'texture_name' => NULL,
                'deny_self_cast' => 0,
                'cast_hidden' => 1,
                'target_team' => NULL,
                'target_type' => NULL,
                'target_flags' => '["DOTA_UNIT_TARGET_FLAG_INVULNERABLE"]',
                'damage_type' => NULL,
                'damage' => NULL,
                'mana_cost' => NULL,
                'gold_cost' => NULL,
                'cooldown' => '["30"]',
                'cast_range' => NULL,
                'cast_point' => '["0.0"]',
                'cast_range_buffer' => NULL,
                'channel_time' => NULL,
                'channel_mana_cost' => NULL,
                'duration' => '["0.5"]',
                'cooldown_group' => 'reflex_core',
                'created_at' => '2017-03-21 16:55:32',
                'updated_at' => '2017-03-21 16:55:32',
                'magic_stick' => 1,
                'is_override' => 0,
            ),
            14 => 
            array (
                'id' => 16,
                'name' => 'Reactive push',
                'base_class' => 'ability_react_3c',
                'behaviour' => '["DOTA_ABILITY_BEHAVIOR_NO_TARGET","DOTA_ABILITY_BEHAVIOR_IMMEDIATE"]',
                'type' => 'DOTA_ABILITY_TYPE_BASIC',
                'texture_name' => NULL,
                'deny_self_cast' => 0,
                'cast_hidden' => 1,
                'target_team' => NULL,
                'target_type' => NULL,
                'target_flags' => '["DOTA_UNIT_TARGET_FLAG_INVULNERABLE"]',
                'damage_type' => NULL,
                'damage' => NULL,
                'mana_cost' => NULL,
                'gold_cost' => NULL,
                'cooldown' => '["30"]',
                'cast_range' => NULL,
                'cast_point' => '["0.0"]',
                'cast_range_buffer' => NULL,
                'channel_time' => NULL,
                'channel_mana_cost' => NULL,
                'duration' => '["0.5"]',
                'cooldown_group' => 'reflex_core',
                'created_at' => '2017-03-21 17:00:45',
                'updated_at' => '2017-03-21 17:00:45',
                'magic_stick' => 1,
                'is_override' => 0,
            ),
            15 => 
            array (
                'id' => 17,
                'name' => 'Self purge',
                'base_class' => 'ability_postact',
                'behaviour' => '["DOTA_ABILITY_BEHAVIOR_NO_TARGET","DOTA_ABILITY_BEHAVIOR_IMMEDIATE"]',
                'type' => 'DOTA_ABILITY_TYPE_BASIC',
                'texture_name' => NULL,
                'deny_self_cast' => 0,
                'cast_hidden' => 1,
                'target_team' => NULL,
                'target_type' => NULL,
                'target_flags' => '["DOTA_UNIT_TARGET_FLAG_INVULNERABLE"]',
                'damage_type' => NULL,
                'damage' => NULL,
                'mana_cost' => NULL,
                'gold_cost' => NULL,
                'cooldown' => '["30"]',
                'cast_range' => NULL,
                'cast_point' => '["0.0"]',
                'cast_range_buffer' => NULL,
                'channel_time' => NULL,
                'channel_mana_cost' => NULL,
                'duration' => NULL,
                'cooldown_group' => 'reflex_core',
                'created_at' => '2017-03-21 19:53:10',
                'updated_at' => '2017-03-21 19:53:42',
                'magic_stick' => 1,
                'is_override' => 0,
            ),
            16 => 
            array (
                'id' => 18,
                'name' => 'Hide',
                'base_class' => 'ability_postact_2',
                'behaviour' => '["DOTA_ABILITY_BEHAVIOR_NO_TARGET","DOTA_ABILITY_BEHAVIOR_IMMEDIATE"]',
                'type' => 'DOTA_ABILITY_TYPE_BASIC',
                'texture_name' => NULL,
                'deny_self_cast' => 0,
                'cast_hidden' => 1,
                'target_team' => NULL,
                'target_type' => NULL,
                'target_flags' => '["DOTA_UNIT_TARGET_FLAG_INVULNERABLE"]',
                'damage_type' => NULL,
                'damage' => NULL,
                'mana_cost' => NULL,
                'gold_cost' => NULL,
                'cooldown' => '["30"]',
                'cast_range' => NULL,
                'cast_point' => '["0.0"]',
                'cast_range_buffer' => NULL,
                'channel_time' => NULL,
                'channel_mana_cost' => NULL,
                'duration' => '["5"]',
                'cooldown_group' => 'reflex_core',
                'created_at' => '2017-03-21 19:58:12',
                'updated_at' => '2017-03-21 19:58:12',
                'magic_stick' => 1,
                'is_override' => 0,
            ),
            17 => 
            array (
                'id' => 19,
                'name' => 'Greater Dispel',
                'base_class' => 'ability_postact_3b',
                'behaviour' => '["DOTA_ABILITY_BEHAVIOR_NO_TARGET","DOTA_ABILITY_BEHAVIOR_IMMEDIATE"]',
                'type' => 'DOTA_ABILITY_TYPE_BASIC',
                'texture_name' => NULL,
                'deny_self_cast' => 0,
                'cast_hidden' => 1,
                'target_team' => NULL,
                'target_type' => NULL,
                'target_flags' => '["DOTA_UNIT_TARGET_FLAG_INVULNERABLE"]',
                'damage_type' => NULL,
                'damage' => NULL,
                'mana_cost' => NULL,
                'gold_cost' => NULL,
                'cooldown' => '["30"]',
                'cast_range' => NULL,
                'cast_point' => '["0.0"]',
                'cast_range_buffer' => NULL,
                'channel_time' => NULL,
                'channel_mana_cost' => NULL,
                'duration' => NULL,
                'cooldown_group' => 'reflex_core',
                'created_at' => '2017-03-21 20:32:45',
                'updated_at' => '2017-03-21 20:32:45',
                'magic_stick' => 1,
                'is_override' => 0,
            ),
            18 => 
            array (
                'id' => 20,
                'name' => 'Postactive Regeneration',
                'base_class' => 'ability_postact_3c',
                'behaviour' => '["DOTA_ABILITY_BEHAVIOR_NO_TARGET","DOTA_ABILITY_BEHAVIOR_IMMEDIATE"]',
                'type' => 'DOTA_ABILITY_TYPE_BASIC',
                'texture_name' => NULL,
                'deny_self_cast' => 0,
                'cast_hidden' => 1,
                'target_team' => NULL,
                'target_type' => NULL,
                'target_flags' => '["DOTA_UNIT_TARGET_FLAG_INVULNERABLE"]',
                'damage_type' => NULL,
                'damage' => NULL,
                'mana_cost' => NULL,
                'gold_cost' => NULL,
                'cooldown' => '["30"]',
                'cast_range' => NULL,
                'cast_point' => '["0.0"]',
                'cast_range_buffer' => NULL,
                'channel_time' => NULL,
                'channel_mana_cost' => NULL,
                'duration' => '["5"]',
                'cooldown_group' => 'reflex_core',
                'created_at' => '2017-03-21 20:45:09',
                'updated_at' => '2017-03-21 20:45:09',
                'magic_stick' => 1,
                'is_override' => 0,
            ),
        ));
        
        
    }
}