<?php

use Illuminate\Database\Seeder;

class StatsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('stats')->delete();
        
        \DB::table('stats')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Health',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'bonus_health',
                'created_at' => '2017-02-24 12:00:00',
                'updated_at' => '2017-03-08 09:33:19',
                'stat_group' => NULL,
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Health regeneration',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'bonus_health_regen',
                'created_at' => '2017-02-24 12:00:00',
                'updated_at' => '2017-02-24 12:00:00',
                'stat_group' => NULL,
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
            'name' => 'Damage block (Melee)',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'block_damage_melee',
                'created_at' => '2017-02-24 12:00:00',
                'updated_at' => '2017-02-24 12:00:00',
                'stat_group' => 'block',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Block chance',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'block_chance',
                'created_at' => '2017-02-24 12:00:00',
                'updated_at' => '2017-02-24 12:00:00',
                'stat_group' => 'block',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
            'name' => 'Damage block (Ranged)',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'block_damage_ranged',
                'created_at' => '2017-02-24 12:00:00',
                'updated_at' => '2017-02-24 12:00:00',
                'stat_group' => 'block',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
            'name' => 'Bash chance (Melee)',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'bash_chance_melee',
                'created_at' => '2017-02-24 12:00:00',
                'updated_at' => '2017-02-24 12:00:00',
                'stat_group' => 'bash',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
            'name' => 'Bash chance (Ranged)',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'bash_chance_ranged',
                'created_at' => '2017-02-24 12:00:00',
                'updated_at' => '2017-02-24 12:00:00',
                'stat_group' => 'bash',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Bash duration',
                'var_type' => 'FIELD_FLOAT',
                'dota_name' => 'bash_duration',
                'created_at' => '2017-02-24 12:00:00',
                'updated_at' => '2017-02-24 12:00:00',
                'stat_group' => 'bash',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Bash damage',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'bonus_chance_damage',
                'created_at' => '2017-02-24 12:00:00',
                'updated_at' => '2017-02-24 12:00:00',
                'stat_group' => 'bash',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Bash cooldown',
                'var_type' => 'FIELD_FLOAT',
                'dota_name' => 'bash_cooldown',
                'created_at' => '2017-02-24 12:00:00',
                'updated_at' => '2017-02-24 12:00:00',
                'stat_group' => 'bash',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Stun duration',
                'var_type' => 'FIELD_FLOAT',
                'dota_name' => 'stun_duration',
                'created_at' => '2017-02-24 12:00:00',
                'updated_at' => '2017-02-24 12:00:00',
                'stat_group' => NULL,
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Strength',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'bonus_str',
                'created_at' => '2017-02-24 13:32:17',
                'updated_at' => '2017-03-03 13:24:23',
                'stat_group' => NULL,
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Damage',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'bonus_damage',
                'created_at' => '2017-02-24 13:33:36',
                'updated_at' => '2017-02-24 13:33:36',
                'stat_group' => NULL,
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Attack speed',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'bonus_attack_speed',
                'created_at' => '2017-02-24 15:15:16',
                'updated_at' => '2017-02-24 15:15:16',
                'stat_group' => NULL,
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Armor',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'bonus_armor',
                'created_at' => '2017-02-24 15:15:33',
                'updated_at' => '2017-02-24 15:15:33',
                'stat_group' => NULL,
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Unholy damage',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'unholy_bonus_damage',
                'created_at' => '2017-02-24 15:16:54',
                'updated_at' => '2017-02-24 15:16:54',
                'stat_group' => 'unholy',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Unholy attack speed',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'unholy_bonus_attack_speed',
                'created_at' => '2017-02-24 15:17:14',
                'updated_at' => '2017-02-24 15:17:14',
                'stat_group' => 'unholy',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'unholy strength',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'unholy_bonus_strength',
                'created_at' => '2017-02-24 15:17:25',
                'updated_at' => '2017-02-24 15:17:25',
                'stat_group' => 'unholy',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Unholy armor',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'unholy_bonus_armor',
                'created_at' => '2017-02-24 15:17:37',
                'updated_at' => '2017-02-24 15:17:37',
                'stat_group' => 'unholy',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
            'name' => 'Unholy health drain (tick)',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'unholy_health_drain_per_tick',
                'created_at' => '2017-02-24 15:18:07',
                'updated_at' => '2017-02-24 15:18:07',
                'stat_group' => 'unholy',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
            'name' => 'Unholy health drain (second)',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'unholy_health_drain_per_second_tooltip',
                'created_at' => '2017-02-24 15:18:27',
                'updated_at' => '2017-02-24 15:18:27',
                'stat_group' => 'unholy',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Toggle cooldown',
                'var_type' => 'FIELD_FLOAT',
                'dota_name' => 'toggle_cooldown',
                'created_at' => '2017-02-24 15:18:46',
                'updated_at' => '2017-02-24 15:18:46',
                'stat_group' => NULL,
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Mana',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'bonus_mana',
                'created_at' => '2017-02-27 17:32:03',
                'updated_at' => '2017-02-27 17:32:03',
                'stat_group' => NULL,
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
            'name' => 'Aoe increase (%)',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'cast_aoe_bonus_percent',
                'created_at' => '2017-02-27 17:32:42',
                'updated_at' => '2017-02-27 17:32:42',
                'stat_group' => NULL,
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
            'name' => 'Spell amp (%)',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'spell_amp',
                'created_at' => '2017-02-27 17:33:24',
                'updated_at' => '2017-02-27 17:33:24',
                'stat_group' => NULL,
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Cast range',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'cast_range_bonus',
                'created_at' => '2017-02-27 17:34:51',
                'updated_at' => '2017-02-27 17:34:51',
                'stat_group' => NULL,
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Agility',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'bonus_agi',
                'created_at' => '2017-02-28 16:58:03',
                'updated_at' => '2017-03-03 13:23:55',
                'stat_group' => NULL,
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Evasion',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'bonus_evasion',
                'created_at' => '2017-02-28 16:58:14',
                'updated_at' => '2017-03-30 07:13:17',
                'stat_group' => NULL,
                'is_percent' => 1,
                'var_name' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
            'name' => 'Move speed (%)',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'bonus_move_speed',
                'created_at' => '2017-02-28 16:58:30',
                'updated_at' => '2017-03-30 07:12:44',
                'stat_group' => NULL,
                'is_percent' => 1,
                'var_name' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Duration',
                'var_type' => 'FIELD_FLOAT',
                'dota_name' => 'duration',
                'created_at' => '2017-02-28 16:58:41',
                'updated_at' => '2017-02-28 16:58:41',
                'stat_group' => NULL,
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Intelligence',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'bonus_int',
                'created_at' => '2017-03-02 10:39:03',
                'updated_at' => '2017-03-03 13:24:45',
                'stat_group' => NULL,
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
            'name' => 'Movement speed (flat)',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'bonus_movement_speed',
                'created_at' => '2017-03-02 10:42:05',
                'updated_at' => '2017-03-02 10:42:05',
                'stat_group' => NULL,
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Bonus selected attribute',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'bonus_stat',
                'created_at' => '2017-03-02 10:45:33',
                'updated_at' => '2017-03-02 10:45:33',
                'stat_group' => NULL,
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Cleave radius',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'cleave_radius',
                'created_at' => '2017-03-02 10:53:37',
                'updated_at' => '2017-03-02 10:53:37',
                'stat_group' => 'cleave',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
            'name' => 'Cleave damage (%)',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'cleave_damage_percent',
                'created_at' => '2017-03-02 10:53:57',
                'updated_at' => '2017-03-02 10:53:57',
                'stat_group' => 'cleave',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
            'name' => 'Cleave width (start)',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'cleave_starting_width',
                'created_at' => '2017-03-02 10:56:45',
                'updated_at' => '2017-03-02 10:56:45',
                'stat_group' => 'cleave',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
            'name' => 'Cleave width (end)',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'cleave_ending_width',
                'created_at' => '2017-03-02 10:57:02',
                'updated_at' => '2017-03-02 10:57:02',
                'stat_group' => 'cleave',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'Cleave distance',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'cleave_distance',
                'created_at' => '2017-03-02 10:57:18',
                'updated_at' => '2017-03-02 10:57:18',
                'stat_group' => 'cleave',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
            'name' => 'Mana regen (%)',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'bonus_mana_regen',
                'created_at' => '2017-03-02 16:14:26',
                'updated_at' => '2017-03-02 16:14:26',
                'stat_group' => NULL,
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'Max Charges',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'max_charges',
                'created_at' => '2017-03-08 09:01:05',
                'updated_at' => '2017-03-08 09:35:05',
                'stat_group' => 'stick',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'Charge radius',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'charge_radius',
                'created_at' => '2017-03-08 09:01:23',
                'updated_at' => '2017-03-08 09:35:10',
                'stat_group' => 'stick',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'Restore Hp/Mp per charge',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'restore_per_charge',
                'created_at' => '2017-03-08 09:01:51',
                'updated_at' => '2017-03-08 09:35:13',
                'stat_group' => 'stick',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'Charge decay',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'charge_decay_time',
                'created_at' => '2017-03-08 09:04:35',
                'updated_at' => '2017-03-08 09:35:26',
                'stat_group' => 'charge_bkb',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'Immunity per charge',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'immunity_time_per_charge',
                'created_at' => '2017-03-08 09:04:54',
                'updated_at' => '2017-03-08 09:35:30',
                'stat_group' => 'charge_bkb',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'Aura health regen',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'aura_health_regen',
                'created_at' => '2017-03-13 07:36:15',
                'updated_at' => '2017-03-13 07:36:15',
                'stat_group' => NULL,
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
            'name' => 'Aura health regen (bonus)',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'aura_health_regen_bonus',
                'created_at' => '2017-03-13 07:36:40',
                'updated_at' => '2017-03-13 07:36:40',
                'stat_group' => 'gg',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'Aura bonus threshold',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'aura_bonus_threshold',
                'created_at' => '2017-03-13 07:37:04',
                'updated_at' => '2017-03-13 07:37:04',
                'stat_group' => 'gg',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'Aura radius',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'aura_radius',
                'created_at' => '2017-03-13 07:37:16',
                'updated_at' => '2017-03-13 07:37:16',
                'stat_group' => NULL,
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'Replenish health',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'replenish_health',
                'created_at' => '2017-03-13 07:37:35',
                'updated_at' => '2017-03-13 07:37:35',
                'stat_group' => 'gg',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'Replenish mana',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'replenish_mana',
                'created_at' => '2017-03-13 07:37:46',
                'updated_at' => '2017-03-13 07:37:46',
                'stat_group' => 'gg',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'Mana restored per creep',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'mana_restore_per_creep',
                'created_at' => '2017-03-13 07:39:07',
                'updated_at' => '2017-03-13 07:39:07',
                'stat_group' => 'gg',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'Aura armor',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'aura_armor',
                'created_at' => '2017-03-13 07:40:28',
                'updated_at' => '2017-03-13 07:40:28',
                'stat_group' => NULL,
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
            'name' => 'Aura armor (bonus)',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'aura_armor_bonus',
                'created_at' => '2017-03-13 07:40:41',
                'updated_at' => '2017-03-13 07:40:41',
                'stat_group' => 'gg',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
            'name' => 'Spell damage (flat)',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'spell_damage',
                'created_at' => '2017-03-13 07:59:18',
                'updated_at' => '2017-03-13 07:59:18',
                'stat_group' => 'gg',
                'is_percent' => 0,
                'var_name' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
            'name' => 'Block chance (Hero)',
                'var_type' => 'FIELD_INTEGER',
                'dota_name' => 'block_chance_hero',
                'created_at' => '2017-03-17 15:37:10',
                'updated_at' => '2017-03-17 15:37:10',
                'stat_group' => NULL,
                'is_percent' => 0,
                'var_name' => NULL,
            ),
        ));
        
        
    }
}