language: php
php:
  - '7.0'
  - '7.1'

services:
  - mysql
  - apache2

install:
  - composer install

cache:
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi php7.0-fpm
  # enable php-fpm
  # sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart

  - mysql -e 'create database storetree;'
  - php artisan db:seed --force
  - php artisan migrate --seed --force
  - php artisan key:generate

script:
  - phpdbg -qrr phpunit
  - phpunit --configuration phpunit.xml --coverage-text

branches:
  only:
    - master
    - laravel